//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DivingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certs
    {
        public int UserID { get; set; }
        public decimal CertID { get; set; }
        public Nullable<System.DateTime> DateArchieve { get; set; }
        public string CertNumber { get; set; }
        public string Issuer { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual User Users { get; set; }
        public virtual Dic_Certs Dic_Certs { get; set; }
    }
}
