//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DivingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dic_WeightOk
    {
        public Dic_WeightOk()
        {
            this.Dives = new HashSet<Dives>();
        }
    
        public byte WeightOkID { get; set; }
        public string WeightOkValue { get; set; }
    
        public virtual ICollection<Dives> Dives { get; set; }
    }
}
