//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DivingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dic_Certs
    {
        public Dic_Certs()
        {
            this.Certs = new HashSet<Certs>();
        }
    
        public decimal CertID { get; set; }
        public string CertName { get; set; }
        public byte Level { get; set; }
        public bool IsGeneral { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Certs> Certs { get; set; }
    }
}
