//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DivingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dives
    {
        public Dives()
        {
            this.Photos = new HashSet<Photos>();
        }
    
        public decimal DiveID { get; set; }
        public int UserID { get; set; }
        public System.DateTime DiveDate { get; set; }
        public Nullable<decimal> Country { get; set; }
        public string Location { get; set; }
        public Nullable<byte> DiveType { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<byte> WeightIsOk { get; set; }
        public Nullable<byte> Tank { get; set; }
        public Nullable<byte> TankStart { get; set; }
        public Nullable<byte> TankEnd { get; set; }
        public Nullable<double> AirTemperature { get; set; }
        public Nullable<double> WaterTemperature { get; set; }
        public Nullable<byte> Visibility { get; set; }
        public Nullable<byte> TotalMinutes { get; set; }
        public Nullable<double> MaxDepth { get; set; }
        public Nullable<byte> FiveMetersMinutes { get; set; }
        public Nullable<byte> SuitType { get; set; }
        public string Comments { get; set; }
        public Nullable<double> DiveX { get; set; }
        public Nullable<double> DiveY { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
    
        public virtual Dic_Countries Dic_Countries { get; set; }
        public virtual Dic_Suit Dic_Suit { get; set; }
        public virtual Dic_Tank Dic_Tank { get; set; }
        public virtual Dic_WeightOk Dic_WeightOk { get; set; }
        public virtual User Users { get; set; }
        public virtual ICollection<Photos> Photos { get; set; }
    }
}
