//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DivingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoImg
    {
        public decimal PhotoID { get; set; }
        public byte[] PhotoVal { get; set; }
    
        public virtual Photos Photos { get; set; }
    }
}
