//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DivingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        public decimal DiveID { get; set; }
        public decimal PhotoID { get; set; }
        public string PhotoName { get; set; }
        public byte[] PhotoThumb { get; set; }
        public string PhotoComment { get; set; }
        public System.DateTime PhotoDate { get; set; }
        public bool Status { get; set; }
    
        public virtual Dives Dives { get; set; }
        public virtual PhotoImg PhotoImg { get; set; }
    }
}
