//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DivingApp.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class DicCert
    {    
        [Key]
        public decimal CertID { get; set; }
        public string CertName { get; set; }
        public byte Level { get; set; }
        public bool IsGeneral { get; set; }
        public string Description { get; set; }
    }
}
