//------------------------------------------------------------------------------
// <auto-generated>
namespace DivingApp.Models.DataModel
{
    using System.ComponentModel.DataAnnotations;

    public class DicDiveTime
    {
        [Key]
        public byte TimeId { get; set; }

        public string TimeValue { get; set; }
    }
}
