//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DivingApp.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Dive
    {    
        [Key]
        public long DiveID { get; set; }

        public DateTime DiveDate { get; set; }

        public Nullable<long> Country { get; set; }

        public string Location { get; set; }

        public Nullable<byte> DiveType { get; set; }

        public Nullable<double> Weight { get; set; }

        public Nullable<byte> WeightIsOk { get; set; }

        public Nullable<byte> Tank { get; set; }

        public Nullable<byte> TankStart { get; set; }

        public Nullable<byte> TankEnd { get; set; }

        public Nullable<double> AirTemperature { get; set; }

        public Nullable<double> WaterTemperature { get; set; }

        public Nullable<byte> Visibility { get; set; }

        public Nullable<byte> TotalMinutes { get; set; }

        public Nullable<double> MaxDepth { get; set; }

        public Nullable<byte> FiveMetersMinutes { get; set; }

        public Nullable<byte> SuitType { get; set; }

        public string Comments { get; set; }

        public Nullable<double> DiveX { get; set; }

        public Nullable<double> DiveY { get; set; }

        public bool Status { get; set; }

        public Nullable<System.DateTime> UpdDate { get; set; }
    
        public virtual DicCountry Countries { get; set; }

        public virtual DicSuit Suit { get; set; }

        public virtual DicTank TankName { get; set; }

        public virtual DicWeightOk WeightOk { get; set; }

        public virtual User User { get; set; }

        public virtual ICollection<Photos> Photos { get; set; }
    }
}
