//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DivingApp.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Photos
    {
        [Key]
        public long PhotoID { get; set; }

        public long DiveID { get; set; }  
             
        public string PhotoName { get; set; }

        public byte[] PhotoThumb { get; set; }

        public string PhotoComment { get; set; }

        public System.DateTime PhotoDate { get; set; }

        public bool Status { get; set; }

        public byte[] PhotoVal { get; set; }
    }
}
